--- CREO TABLA EMAILS ---
CREATE TABLE emails (
	direccion VARCHAR(50),
	persona VARCHAR (255)
);

--- LE AÑADO UN IDENTIFICADOR ---
ALTER TABLE emails
ADD COLUMN identificador INT AUTO_INCREMENT PRIMARY KEY FIRST;
SHOW TABLES;

