## EN MY SQL CUANDO SALIMOS SE BORRA ##
## ES MEJOR TENER UN BLOC DE NOTAS DONDE COPIAMOS LOS COMANDOS QUE USAMOS, PARA LLEVAR UN REGISTRO ##
sudo mysql -u root -p
# MOSTRAMOS LAS DATABASE #
SHOW DATABASES;
# CREAMOS LA DATABASE #
	

## CON ESTE COMANDO, ENTRAMOS EFECTIVAMENTE EN LA BASE DE DATOS ##
USE empresadam;

# MOSTRAMOS LAS TABLAS #
SHOW TABLES;

# CREAMOS UNA TABLA
CREATE TABLE clientes(
	dni VARCHAR(9),
	nombre VARCHAR(50),
	apellidos VARCHAR(255),
	email VARCHAR(100)
);
# INSERTAR DATOS EN LA TABLA #
INSERT INTO Cliente VALUES(
	"12345678Z",
	"Pepe",
	"Gomez",
	"pepe@gmail.com"
);

# MOSTRAMOS TODOS LOS DATOS DE LA TABLA #
SELECT * FROM clientes;

# CAMBIAMOS UN DATO #
UPDATE clientes
SET dni = "11111111A"
WHERE nombre = "Valentin";

UPDATE clientes
SET apellidos = "DeGennaro"
WHERE nombre = "Valentin";

# BORRAMOS UN ELEMENTO DE LA LISTA#
DELETE FROM clientes
WHERE dni = "11111111A";


DESCRIBE clientes;
ALTER TABLE clientes
ADD COLUMN identificador INT AUTO_INCREMENT PRIMARY KEY FIRST;

ALTER = ALTERA
TABLE = TABLA 
CLIENTES = LA TABLA QUE QUIERO ALTERAR
ADD = LA OPERACION QUE QUIERO REALIZAR
COLUMN = QUIERO AÑADIR UNA COLUMNA
IDENTIFICADOR = ES EL NOMBRE DE LA COLUMNA QUE QUIERO AÑADIR
INT = EL TIPO DE DATO DE LA COLUMNA (ENTERO)
AUTO_INCREMENT = EL NUMERO VA A CRECER AUTOMATICAMENTE
FIRST = SI HAY VARIAS, ESTA TIENE LA PREFERENCIA

DESCRIBE clientes;

INSERT INTO clientes VALUES(
	NULL,
	"87654321A",
	"Juan",
	"Lopez",
	"lopez@gmail.com"
);

## ES IMPORTANTE MANTENER LIMPIA LA BASE DE DATOS ##


